version: "3"

services:

    service1:
        build: 
            context: ./Service1/
            dockerfile: Dockerfile
        ports: 
            - "5000:5000"
        networks:
            - main_network

    service2:
        build: 
            context: ./Service2/
            dockerfile: Dockerfile
        ports: 
            - "5001:5001"
        networks:
            - main_network

    service3:
        build: 
            context: ./Service3/
            dockerfile: Dockerfile
        ports: 
            - "5002:5002"
        networks:
            - main_network

    service4:
        build: 
            context: ./Service4/
            dockerfile: Dockerfile
        ports: 
            - "5003:5003"
        networks:
            - main_network

networks:
    main_network:
        driver: bridge