version: "3"

services:

    service1:
        image: microservice1:4
        ports: 
            - "5000:5000"
        networks:
            - main_network

    service2:
        image: microservice2:3
        ports: 
            - "5001:5001"
        networks:
            - main_network

    service3:
        image: microservice3:3
        ports: 
            - "5002:5002"
        networks:
            - main_network

    service4:
        image: microservice4:4
        ports: 
            - "5003:5003"
        networks:
            - main_network

networks:
    main_network:
        driver: bridge