version: "3"

services:

    service1:
        image: adelina09/service1
        ports:
            - "5000:5000"
        networks:
            - main_network
        deploy:
            replicas: 3

    service2:
        image: adelina09/service2
        ports: 
            - "5001:5001"
        networks:
            - main_network
        deploy:
            replicas: 3

    service3:
        image: adelina09/service3
        ports: 
            - "5002:5002"
        networks:
            - main_network
        deploy:
            replicas: 3

    service4:
        image: adelina09/service4
        ports: 
            - "5003:5003"
        networks:
            - main_network
        deploy:
            replicas: 3
networks:
    main_network:
        driver: overlay